Fix targdiff
alexeilebedev/openacr pull request #39
Opened 2023-08-14 21:52 UTC by alexeilebedev

2023-08-16 22:25 UTC, vparizhs commented
both master and fix-targdiff branch look broken. Just running it in either branch gives these errors... No use instructions are given so I don't really know how it supposed to behave and what it does... Please add an example...

$ targ-diff
bin/targ-diff: 8: [: unexpected operator
bin/targ-diff: 14: [: 0: unexpected operator
Cloning into '.tempgit'...
done.
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

2023-08-16 22:27 UTC, vparizhs requested changes
1. the utility produces errors when run - see below.
2. Please add a use example - it is hard to see what it is supposed to do...

$ targ-diff
bin/targ-diff: 8: [: unexpected operator
bin/targ-diff: 14: [: 0: unexpected operator
Cloning into '.tempgit'...
done.
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

2023-09-04 10:29 UTC, polovinkin-alexey commented on bin/targ-diff
> -BRANCH=$(git-current-branch)
I  guess  this command or executable is missing on the repo.

2023-09-04 10:32 UTC, polovinkin-alexey commented
PR title is irrelevant to the majority of changes.

2023-09-23 05:27 UTC, alexeilebedev commented
Closed for now, will reimplement targdiff in a different way

2023-09-23 05:27 UTC, closed without merging