June2024
alexeilebedev/openacr pull request #87
Opened 2024-06-28 19:33 UTC by alexeilebedev

2024-07-01 09:01 UTC, polovinkin-alexey requested changes
LICENCE removed? ARND scripts and CI stuff leaked, X2 leaked

2024-08-13 08:48 UTC, ali5h commented
landing this?

2024-08-13 20:41 UTC, ali5h requested changes
> Reviewed 220 of 977 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexeilebedev/openacr/87)* status: 221 of 977 files reviewed, 3 unresolved discussions (waiting on @alexeilebedev)

___
*[`data/amsdb/streamtype.ssim` line 2 at r2](https://reviewable.io/reviews/alexeilebedev/openacr/87#-O49tBfzDMihMruceD_3:-O49tBfzDMihMruceD_4:b32ww0) ([raw file](https://github.com/alexeilebedev/openacr/blob/dc0378f7f597ac87d3919d7714e25dcd9fd70d0b/data/amsdb/streamtype.ssim#L2)):*
> ```
> amsdb.streamtype  streamtype:0  id:0  comment:"No stream"
> amsdb.streamtype  streamtype:ack  id:10  comment:"Commit Ack messages"
> ```

rm
___
*[`gclitest/github_token.base64` line 1 at r2](https://reviewable.io/reviews/alexeilebedev/openacr/87#-O49vKYJ4c1K8NZEB-in:-O49vKYJ4c1K8NZEB-io:byojqrm) ([raw file](https://github.com/alexeilebedev/openacr/blob/dc0378f7f597ac87d3919d7714e25dcd9fd70d0b/gclitest/github_token.base64#L1)):*
> ```
> Z2l0aHViX3BhdF8xMUFFTEhaT1kwdUUwcGdIakQ0bkpyX0Z0RUFvOWx4SVUzcmJtN0JtdFVYVVFr
> ```

rm? what is this for??
___
*[`gclitest/gitlab_token.base64` line 1 at r2](https://reviewable.io/reviews/alexeilebedev/openacr/87#-O49vUlA9gV8Knc5F_2M:-O49vUlA9gV8Knc5F_2N:b32ww0) ([raw file](https://github.com/alexeilebedev/openacr/blob/dc0378f7f597ac87d3919d7714e25dcd9fd70d0b/gclitest/gitlab_token.base64#L1)):*
> ```
> Z2xwYXQtSGYzOFJCMko5R1VaUmhjNTRGQ3MK
> ```

rm


<!-- Sent from Reviewable.io -->

2024-10-26 11:15 UTC, polovinkin-alexey approved these changes

2024-10-30 23:39 UTC, ali5h approved these changes

2024-10-31 15:06 UTC, merged